apiVersion: v1
kind: Service
metadata:
  name: clouddeploy-service
  namespace: clouddeploy

spec:
  type: NodePort

  selector:
    app: clouddeploy

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080